import sys
sys.path.append("../Services")
from b2bcliente import Regexseaker
reg = Regexseaker("../Services/b2bcliente/facturaskeys.json")

frases = ["numero de cuenta abc345",
          "el número de cuenta es Sad345",
          "con número de cuenta 5555",
          "cuenta con número xsa243",
          "cuenta de numero aaxr243210S01",
          "cuenta de clave 22",
          "cuenta con matrícula igual a x243421",
          "número de cuenta con número igual a aagr223455",
          "número de cuenta con 1214125 como numero",
          "cuenta 342243x",
          "la cuenta es 234342s",
          "cuenta de numero 32422a",
          "con cuenta igual a WWD224",
          "con cuenta de matricula 3424232s",
          "cuenta con numeración igual 2342211",
          "Con prefijo número 23",
          "Prefijo con matricula 1223",
          "Cuyo prefijo es werw",
          "donde se lea que el prefijo es 2a42",
          "para serie igual a x",
          "y donde el prefijo es a4",
          "y tambien con est como prefijo",
          "23a es el prefijo",
          "la serie está asignada a z443",
          "para la asignacón del prefijo tenemos al z43",
          "3343 se lee como prefijo",
          "prefijo igual a 4343",
          "prefijo ass",
          "prefijo sea x",
          "nit con clave fafafll",
          "nit con número AAGR860628S34",
          "NIT de número x243421",
          "NIT de numero aaxr243210S01",
          "adquiriente es el 3424242",
          "nit de clave 22",
          "nit adquiriente con numero igual a x243421",
          "nit adquiriente con número igual a aagr223455",
          "nit adquiriente con aaagg como numero",
          "nit con x como número",
          "nit clave aagr342243",
          "nit es 100",
          "nit x",
          "con nit igual a WWDA912122r44",
          "con nit adquiriente igual a aagr860628s34",
          "el nit adquiriente es y",
          "rfc con clave fafafll",
          "rfc con número AAGR860628S34",
          "rfc de número x243421",
          "rfc de numero aaxr243210'S01",
          "rfc de clave 22",
          "rfc adquiriente con numero igual a x243421",
          "rfc adquiriente con número igual a aagr223455",
          "rfc adquiriente con aaagg como numero",
          "rfc con x como número",
          "rfc clave aagr342243",
          "rfc es 100",
          "en donde el rfc sea x",
          "con rfc igual a WWDA912122r44",
          "con rfc adquiriente igual a aagr860628s34",
          "con 51521 como nit adquiriente",
          "6623 es el nit adquiriente",
          "x igual al nit adquiriente",
          "2 está asignado como nit",
          "el rfc adquiriente es y",
          "documento con numero x",
          "documento con número y",
          "documento de numero x",
          "documento de número 22",
          "documento con numero igual a x",
          "documento con número igual a e",
          "documento con aaagg como numero",
          "documento con x como número",
          "numero de documento es 100",
          "número de documento es 100",
          "con número de documento x",
          "con numero de documento a",
          "el numero de documento es y",
          "12 es el numero de documento",
          "factura con numero de",
          "factura con número a",
          "nota de numero x",
          "nota de número 22",
          "factura con numero igual a x",
          "factura con número igual a e",
          "crédito con aaagg como numero",
          "crédito con A3 como número",
          "número de crédito es 100",
          "numero de crédito es 100",
          "con número de crédito x",
          "con numero de crédito a",
          "el numero de la nota es y2",
          "12 es el numero de la nota",
          "matricula de documento sea casa",
          "Con número de documento número 23",
          "con número de documento al calce de 443",
          "y también con 424545 como número de documento",
          "2342545 es el número de documento",
          "el numero de documento está asignado como 34433443",
          "el numero de documento está asignado a CU",
          "el numero de documento asignado a CU",
          "para la asignacón del numero de documento tenemos al 433344343",
          "434343 se lee como numero de documento",
          "Con numero de documento 23",
          "documento cuyo numero es werwer",
          "con numero al calce de 443",
          "donde se lea que el numero es 23423542",
          "y donde el numero es 232434",
          "y tambien con 424545 como numero de documento",
          "2342545 es el numero de documento",
          "para la asignación del numero tenemos al 433344343",
          "434343 se lee como numero",
          "numero igual a 34434343",
          "numero de factura 4334433",
          "numero de facturas 1311324",
          "documento sea inicializando",
          "Dame las facturas",
	  "de tipo factura",
	  "quiero las notas",
          "quiero notas de credito con tipo de documento factura",
          "dame las notas con prefijo factura",
          "las facturas con número de documento nota",
          "dame las facturas con prefijo notas",
          "quiero las notas de credito con prefijo factura",
          "quiero las facturas que digan nota como prefijo",
          "dame los documentos facturas",
          "necesito documentos de tipo factura que sean notas",
          "Dame los documentos de tipo factura con acuse pendiente",
          "quiero las notas con estado aceptado",
          "quiero las facturas con estado abierto",
          "dame los documentos de tipo notas de credito",
          "documentos que sean facturas",
          "los documentos que sean de tipo nota",
          "los documentos que sean notas",
          "tipo de documento nota",
          "documento tipo facturas",
          "los documentos son notas",
          "documentos que son facturas",
          "el documento de tipo nota",
          "los documentos son facturas",
          "el tipo de documento es nota",
          "son facturas con prefijo nota",
          "son facturas con prefijo son notas",
          "son facturas con prefijo es nota",
          "es factura con prefijo nota",
          "es nota con prefijo la factura",
          "es nota con prefijo factura",
          "para nota con prefijo factura",
          "de nota con prefijo de factura",
          "para nota con prefijo de factura",
          "para nota con prefijo es factura",
          "para nota con prefijo factura"]

fields = ["NoDocumento", "Prefijo", "Cuenta", "NitAdquirienteMex",
          "Tipo", "Estado", "Acuse"]

for exp in frases:
    print(exp)
    res = [reg.seakexpresion(exp, field)[0] for field in fields]
    print(["{0}: {1}".format(field, resi) for field, resi in zip(fields, res)
           if resi is not None])
