run extraer_frases.py
model.most_similar("facturas")
model.most_similar("notas")
model.most_similar("nota")
model.n_similarity("dame las notas".split(), "dame las facturas".split())
model.n_similarity("dame las notas".split(), "dame las facturas recibidas".split())
model.n_similarity("quiero las facturas con acuse recibido".split(), "dame las facturas recibidas".split())
model.n_similarity("quiero las facturas con acuse recibidas".split(), "dame las facturas recibidas".split())
model.n_similarity("quiero las facturas con acuse rechazado".split(), "dame las facturas recibidas".split())
tphraser
list(tphraser)
list(tphraser)
tphraser[all_sentences]
list(tphraser[all_sentences])
word_vectors = model.wv
del model
word_vectors.vocab
word_vectors.build_vocab
from gensim.models import Word2Vec
model = Word2Vec(min_count=1)
model.build_vocab(word_vectors)
model.build_vocab(word_vectors.vocab)
model.train(word_vectors.vocab, total_examples=model.corpus_count, epochs=model.iter)
model.build_vocab(all_sentences)
model.build_vocab(tphraser[all_sentences])
model.build_vocab(tphraser)
all_sentences[:3]
model.build_vocab(all_sentences)
model.train(all_sentences, total_examples=model.corpus_count, epochs=model.iter)
model.most_similar("gato")
model.most_similar("facturas")
model.build_vocab(word_vectors.vocab)
model.train(word_vectors.vocab, total_examples=model.corpus_count, epochs=model.iter)
model.n_similarity(["gato"])
model.n_similarity("gato")
model.n_similarity("gato", "perro")
model.n_similarity("gato", "rata")
model.n_similarity("gato", "gata")
model.n_similarity("gato", "animal")
model.n_similarity("gato", "tijera")
model.n_similarity("gato", "hombre")
model.n_similarity("gato", "casa")
model.n_similarity("gato", "Nueva York")
model.n_similarity("gato", "Nueva")
model.n_similarity("gato", "nuevo")
model.n_similarity("gato", "amor")
model.n_similarity("el gato está limpio".split(), "quiero las facturas".split())
model.n_similarity("gato está limpio".split(), "quiero las facturas".split())
word_vectors.n_similarity("gato está limpio".split(), "quiero las facturas".split())
word_vectors.n_similarity("gato está limpio".split(), "quiero las facturasde hoy".split())
word_vectors.n_similarity("gato está limpio".split(), "quiero las facturas de hoy".split())
